.gitignore
data/firebase-data.json

- Added **Vatsal Trivedi** and **Dixita Ganatra** as a Creative team member
- Added ServiceAccount directory in gitignore

Added Creative Team in Team page, Update gitignore

---

data/firebase-data.json
npm-debug.log
src/elements/speakers-block.html
src/hoverboard-app.html
src/pages/speakers-page.html

Added Social Media, Content Writer in Team page
- Added Jignesh, Manthan, Dhruv and Abhishek in Social Media Team
- Added Hiral and Pritha in Content Writer Team
SHOW speakers list, Announce Speakers 1 to 12
- Uncomment speakers list UI from speakers -block, -page
- REMOVE unveilSoon content from UI

Added Social Media, Content Writer in Team page, SHOW speakers list and Announce Speakers 1 to 12

---

data/firebase-data.json
data/resources.json
src/elements/tickets-block.html
src/pages/home-page.html

- SHOW tickets UI from tickets-block on home page
- Add ticket purchase URL
- Update database with ticket details

Announce Tickets for Early birds and Regular

---

public/data/firestore-data.json

- Second set of speakers
- adit_lal
- anubhav_singh
- pranay_patel
- chintan_khetiya
- samyak_jain

[Feat] Announcement of Speakers set #2

---

public/data/firestore-data.json

- Third set of speakers
- abhilasha_vyas
- ishan_sharma
- priya_sindkar
- paresh_mayani
- abhishek_desai
- nikita_lalwani
- jaykumar_joshi
- Updated some of speakers details

[Feat] Announcement of Speakers set #3, Updated speaker details 

---

README.md
public/data/resources.json
public/data/settings.json

- Refactor : update readme file with Job Opportunities listing details
- Refactor: total participant count

[Feature] Implemented Job openings feature 

---

public/data/job-openings-data.json

Add iTechOps job openings

---

.gitignore
public/data/firestore-data.json

- Added Previous Speaker details ( 2019 )
- Added `.idea` folder in .gitignore for JetBrains IDE

[Update] Added previous speakers details (DevFestAhm19)

---

public/data/firestore-data.json

- Second set of speakers
- vishal_virani

[Feat] Announcement of Speakers set #4

---

public/data/job-openings-data.json

7Span jobs added

---

public/data/job-openings-data.json

Srashtasoft Logo size updated according to design.

Srashtasoft Logo size updated according to design

---

public/data/job-openings-data.json

Adding recruitmentsmart job posting

Adding recruitmentsmart job posting

---

public/data/job-openings-data.json

Update job listing for Anglara Digital Solutions

---

docs/default-firebase-data.json
public/data/firestore-data.json
src/elements/speakers-block.ts
src/models/speaker.test.ts
src/models/speaker.ts

- static position added for rockstar speakers using the `rockstarSpeakerOrder` key
- change test cases accordingly to the above change.

[Feature] Static position added for rockstar speakers in Home

---

package.json
public/data/firestore-data.json
scripts/firestore-init/team.ts
src/models/team.ts
src/store/teams-members/selectors.ts

- added volunteers' details on the team page in 3 group
1. Registration and Swags Team
2. Content Writer Team
3. Speaker Buddy Team

[Feature] Added volunteers details on team page

---

public/data/firestore-data.json
src/store/teams-members/selectors.ts

- alphabetically sort removed from core team member

[Feature] Alphabetically sort removed from core team member

---

public/data/job-openings-data.json

Added more job opening positions in 7Span

Added more positions

---

public/data/job-openings-data.json

Jobs added by Sufalam

---

public/data/job-openings-data.json

Added Job Description for QDev Technolab

Added Job Description for QDev Technolab

---

public/data/job-openings-data.json

Added Oneclick IT Consultancy in Job openings json file.

Adding Oneclick IT Consultancy in Job Openings

---

public/data/job-openings-data.json

Change Company Logo URL for QDev Technolab

Change Company Logo URL for QDev Technolab

---

public/data/job-openings-data.json

Added Job openings behalf of Codiste Pvt LTD.

Added Job openings behalf of Codiste.

---

public/data/job-openings-data.json

Reverts GDGAhmedabad/devfestahm#177

Revert "Update job-openings-data.json"

---

.gitignore
public/data/job-openings-data.json

Update company logo to look proper in view with center crop image.

Update Company Logo

---

public/data/job-openings-data.json

Added AppStoneLab Technologies LLP (SURAT) in job-openings-data.json

Added AppStoneLab in job-openings-data.json

---

public/data/job-openings-data.json

The wide logo was not looking good. fixed the logo and changed the hiring banner to make it more consistent with design.

Update: Saleshandy logo fixed based on resolution

---

public/data/job-openings-data.json

Update job-openings-data.json for Inferenz Tech

---

public/data/firestore-data.json

- Add presentation links in 2022 sessions

[Feature] Added presentation links of DevFestAhm22 sessions

---

public/data/job-openings-data.json

PR is against develop branch. 
list of openings along with internships and company bio added as per instructions.

Job Openings for Trentium Solution

---

public/data/firestore-data.json

- madhu_vadlamani
- tanvi_sau
- debasmita_sarkar

[Feat] Announce Speakers and Sessions 

---

src/elements/schedule-day.ts
src/elements/session-element.ts

Update: --tracks-number from 3 to 5

[Fix] Schedule page UI fix for more than 3 tracks

---

public/data/job-openings-data.json

iTechOps - Update job-openings-data.json

iTechOps - Update job-openings-data.json

---

public/data/job-openings-data.json

Added Company info, company bio, company logo & compnies's current openings with experience

Job Posting for Webmobtech company

---

public/data/job-openings-data.json

Job Openings for AppAspect Technologies Pvt Ltd.

Job Openings for AppAspect Technologies Pvt Ltd.

---

public/data/job-openings-data.json

Reverts GDGAhmedabad/devfestahm#277

Revert "iTechOps - Update job-openings-data.json" due to merge in `main` and `develop`

---

public/data/firestore-data.json

Twitter link of [Madhu Vadlamani](https://devfest.gdgahmedabad.com/speakers/madhu_vadlamani) is showing 404.

[Fix] [Speaker] Social Link (Twitter) of Madhu

---

public/data/job-openings-data.json

Fixed
- Correct Logo URL
- Correct LinkedIn Page URL

Update json data for DataSlush 

---

public/data/firestore-data.json

Added Twitter of harsh_goyal speaker.

[Speaker] [Socials]  Twitter for harsh_goyal speaker

---

package.json
scripts/updatePreviousSpeakers.js

Run below command to update previous speakers 
`npm run update:previousSpeakers`

[Feature] add script to update previous speakers with their sessions

---

README.md

```diff
- Add your Job openings JSON object [here]
+ Add your Profile JSON object [here]
```

Small text change in Meet the Talent Section

---

public/data/meet-the-talent.json

Listed my profile data to the meet-the-talent.json file.

[Add] Yash Parikh in meet-the-talent.json

---

public/data/meet-the-talent.json

Updated meet talent json by adding himanshu dudhat profile

feat: added himanshu dudhat profile to the talent json

---

public/data/job-openings-data.json

[Add] Job Openings for Linearloop and Betterbugs #371

---

public/data/meet-the-talent.json

I added my json details to PR Thank you give a chance to present ourselves in front of the world.

Add json of Jaydip Umaretiya to meet the talent

---

public/data/meet-the-talent.json

Update meet-the-talent.json with Hitesh Patel

---

public/data/job-openings-data.json

Update job-openings-data.json for Recruitment Smart Company

Update job-openings-data.json for Recruitment Smart Company

---

public/data/meet-the-talent.json

- Adding bio details in Meet The talent JSON file. | Savan Patel

Savan Patel | Meet the Talent

---

public/data/job-openings-data.json

```diff
- We are here to welcome you with an open arms! Looking for a community of bockchain beleivers? Join us and let's make a difference.
+ We are here to welcome you with open arms! Looking for a community of blockchain believers? Join us and let's make a difference.
```

Spell fix in Job Openings

---

public/data/meet-the-talent.json

Update meet-the-talent.json with Rajveer Rathod

---

public/data/meet-the-talent.json

Update meet-the-talent.json (#1)

---

public/data/job-openings-data.json

Add job openings for Skylark Drones

Add job openings for Skylark Drones

---

public/data/meet-the-talent.json

Add my profile json to meet_the_talent.json

Divya senior flutter dev

---

public/data/meet-the-talent.json

Added an object for Sanket Modi.

Update meet-the-talent.json by adding object for Sanket Modi

---

public/data/job-openings-data.json

Company Website [Multipl.in](https://multipl.in)

Added Go-Lang Job-Opening for Multipl Fintech Solutions

---

public/data/meet-the-talent.json

I updated the new image and added my website to the .json file.

Update Jaydip Umaretiya image and add website link into meet-the-talent.json

---

public/data/job-openings-data.json
public/data/meet-the-talent.json

- added all the Job Openings available on the careers page of Crest Data (Ahmedabad).
- added the Meet the Talent data for myself (Shubham Sareliya)

Added Job Openings (Crest Data) & Meet the Talent Data (Shubham Sareliya)

---

public/data/firestore-data.json

Updated:
- Chetan Hirapara bio
- Vishal Virani session title
- Poonam Jha session description

[Update] speaker bio and session details

---

public/data/firestore-data.json

Current
```
Ganga - AI/ML
Yamuna - WEB
Jamana - Startup
Sarsvati - Mobile
```
It will be updated to
```
Narmada - AI/ML
Ganga - WEB
Sabarmati - Startup
Yamuna - Mobile
```

[Update] Tracks Room

---

public/data/job-openings-data.json

Added Codemech Solutions's Job Openings config object

Added Codemech Job Openings to job-openings-data.json

---

public/data/meet-the-talent.json

updated profile name, bio and imgUrl

Update meet-the-talent.json in Sohan Paliyal

---

public/data/meet-the-talent.json

Upadate profile picture 

---

public/data/meet-the-talent.json

#478 PR data, Created newer on due to merge conflicts mistake

[Add] VivekFaldu in Meet the Talent
